# Generated by Django 5.0.4 on 2024-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image',
            field=models.ImageField(default='static/user_images/person.svg', upload_to='static/user_images'),
        ),
    ]
