# Generated by Django 5.0.4 on 2024-04-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_age_customuser_gender_customuser_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cover_pic', models.FileField(upload_to='media/%Y/%m/%d')),
                ('artist', models.TextField()),
                ('category', models.TextField()),
                ('decription', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
